[package]
name = "repin-direct-search"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
repin-core.workspace = true
repin-protocol.workspace = true
regex.workspace = true
thiserror.workspace = true
tracing.workspace = true
