[package]
name = "repin-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
repin-core.workspace = true
repin-protocol.workspace = true
repin-runtime.workspace = true

[dev-dependencies]
tempfile.workspace = true
