[package]
name = "repin-indexing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
publish = false

[dependencies]
repin-core.workspace = true

[dev-dependencies]
repin-fs.workspace = true
repin-packs.workspace = true
repin-store-sqlite.workspace = true
tempfile.workspace = true
